version: '3.8'
services:
  bot:
    build:
      context: ./tg_bot
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - BOT_TOKEN=<your-bot-token>
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=meetup_db
      - DB_USER=postgres_user
      - DB_PASSWORD=postgres_password
    # restart: always

  db:
    image: postgres
    environment:
      - POSTGRES_DB=meetup_db
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin_password
    ports:
      - 8080:80
    # restart: always

volumes:
  db_data:
